

# This file was *autogenerated* from the file dilithium.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_375 = Integer(375); _sage_const_64 = Integer(64); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_325 = Integer(325); _sage_const_80 = Integer(80); _sage_const_5 = Integer(5); _sage_const_275 = Integer(275); _sage_const_96 = Integer(96); _sage_const_175 = Integer(175); _sage_const_120 = Integer(120); _sage_const_256 = Integer(256); _sage_const_8380417 = Integer(8380417); _sage_const_14 = Integer(14); _sage_const_60 = Integer(60); _sage_const_523776 = Integer(523776); _sage_const_261888 = Integer(261888); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from cryptography.hazmat.primitives import hashes 
import os

class Weak:
    k = _sage_const_3 
    l = _sage_const_2 
    eta = _sage_const_7 
    beta = _sage_const_375 
    omega = _sage_const_64 

class Medium:
    k = _sage_const_4 
    l = _sage_const_3 
    eta = _sage_const_6 
    beta = _sage_const_325 
    omega = _sage_const_80 

class Recommended:
    k = _sage_const_5 
    l = _sage_const_4 
    eta = _sage_const_5 
    beta = _sage_const_275 
    omega = _sage_const_96 

class VeryHigh:
    k = _sage_const_6 
    l = _sage_const_5 
    eta = _sage_const_3 
    beta = _sage_const_175 
    omega = _sage_const_120 

class InvalidSignature(Exception):
    pass

class Dilithium:
    def __init__(self, params=Recommended):
        # Define Parameters
        self.n = _sage_const_256 
        self.q = _sage_const_8380417 
        self.d = _sage_const_14 
        self.weight = _sage_const_60 
        self.gamma1 = _sage_const_523776  #(self.q-1) / 16
        self.gamma2 = _sage_const_261888  #self.gamma1 / 2
        self.k = params.k
        self.l = params.l
        self.eta = params.eta
        self.beta = params.beta
        self.omega = params.omega

        # Define Fields
        Zq = GF(self.q)['x']; (x,) = Zq._first_ngens(1)
        self.Rq = Zq.quotient(x**self.n+_sage_const_1 )

        # Generate Keys
        self.A = self.expandA()
        self.s1 = self.sample(self.eta, self.l)
        self.s2 = self.sample(self.eta, self.k)
        self.t = self.A * self.s1 + self.s2
        # Public Key : A, t
        # Private Key : s1, s2    

    def sign(self, m):
        y = self.sample(self.gamma1-_sage_const_1 , self.l)
        w1 = self.high_bits(self.A * y, _sage_const_2  * self.gamma2)

        #print(w1)

    def verify(self):
        pass

    ########### Auxiliar Functions ###########

    # The function ExpandA maps a uniform seed  ∈ {0, 1}^256 to a matrix A ∈ Rq^k×l
    def expandA(self):
        # Na submissão original assume-se ρ como uma
        # seed uniforme para amostrar aleatoriamente
        # neste caso considera-se que `random_element`
        # tem o valor equivalente da seed internamente
        mat = [ self.Rq.random_element() for _ in range(self.k*self.l) ]
        return matrix(self.Rq, self.k, self.l, mat)

    def sample(self, coef_max, size):
        def rand_poly():
            return self.Rq([randint(_sage_const_0 ,coef_max) for _ in range(self.n)])

        vector = [ rand_poly() for _ in range(size) ]

        # Vectores sao representados sob
        # a forma de matrizes para permitir as 
        # operações com a matriz A
        return matrix(self.Rq,size,_sage_const_1 ,vector)

    def high_bits(self, r, alfa):
        r1, r0 = self.decompose(r,alfa)
        return r1

    def low_bits(self, r, alfa):
        r1, r0 = self.decompose(r,alfa)
        return r0

    def decompose(self, r, alfa):
        # Nota: Na submissão original é assumido
        # que as operações no decompose são aplicadas
        # a cada coeficiente.
        r0_poly = []
        r1_poly = []
        for c in r:
            print("c",c)
            c = mod(c,int(self.q))
            r0 = mod(c,int(alfa))
            if c - r0 == self.q - _sage_const_1 :
                r1 = _sage_const_0 
                r0 = r0 - _sage_const_1 
            else:
                r1 = (r - r0) / int(alfa)
            r0_poly.push(r0)
            r1_poly.push(r1)
        return (Rq(r1_poly),Rq(r0_poly))

dilithium = Dilithium(params=Weak)
dilithium.sign(None)



######################################################

#def H(zeta):
#    sha3 = hashes.Hash(hashes.SHAKE256(int(32)))
#    sha3.update(zeta)
#    return sha3.finalize() 

#zeta = os.urandom(32)

#print(H(zeta))

